name: Push Artifact to AWS CodeArtifact

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      DOMAIN: py-domain
      REPOSITORY: py-repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: check python version
        run: |
          python --version
          pip --version

      - name: run python source-code
        run: python main.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Configure pip for CodeArtifact
        run: |
          aws codeartifact login --tool pip --repository ${{env.REPOSITORY}} --domain ${{env.DOMAIN}}

      - name: Generate CodeArtifact Authorization Token
        run: |
          aws codeartifact get-authorization-token --domain ${{env.DOMAIN}} --query authorizationToken --output text
      
      - name: Calculate SHA256 hash
        id: sha256
        run: |
          ls -la
          sha256sum main.py > main.sha256
          cat main.sha256
          echo "::set-output name=sha256::$(awk '{print $1}' main.sha256)"

      - name: Publish to CodeArtifact
        run: | 
          aws codeartifact publish-package-version \
          --domain ${{env.DOMAIN}} \
          --repository ${{env.REPOSITORY}} \
          --format pypi \
          --package main.py \
          --package-version 1.0.0 \
          --asset-name main.py \
          --asset-content ./main.py \
          --asset-sha256 "${{ steps.sha256.outputs.sha256 }}" \
          --region us-east-1
          
        # --namespace generic_artifacts \