name: Push Artifact to AWS CodeArtifact

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      DOMAIN: py-domain
      REPOSITORY: py-repo
      REGION: us-east-1
      PACKAGE_VERSION: 1.0.0
      PACKAGE_NAME: main.tar.gz
      NAMESPACE: py_generic_artifacts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: zipping python source-code with tar
        run: |
          tar -czvf main.tar.gz main.py ChessEngine.py ChessGame.py requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.REGION}} 

      # - name: Login & Generate Authorization Token for CodeArtifact
      #   run: |
      #     # Configure pip for CodeArtifact
      #     aws codeartifact login --tool pip --repository ${{env.REPOSITORY}} --domain ${{env.DOMAIN}}

      #     # Generate CodeArtifact Authorization Token
      #     aws codeartifact get-authorization-token --domain ${{env.DOMAIN}} --query authorizationToken --output text
      
      ## add condition##
      
      - name: Calculate SHA256 hash
        id: sha256
        run: |
          sha256sum ${{env.PACKAGE_NAME}} > main.sha256
          cat main.sha256
          echo "::set-output name=sha256::$(awk '{print $1}' main.sha256)"

      - name: Publish to CodeArtifact
        run: | 
          aws codeartifact publish-package-version \
          --domain ${{env.DOMAIN}} \
          --repository ${{env.REPOSITORY}} \
          --format generic \
          --package ${{env.PACKAGE_NAME}} \
          --package-version ${{env.PACKAGE_VERSION}} \
          --asset-name ${{env.PACKAGE_NAME}} \
          --asset-content ./${{env.PACKAGE_NAME}} \
          --asset-sha256 "${{ steps.sha256.outputs.sha256 }}" \
          --namespace ${{env.NAMESPACE}} \
          --region ${{env.REGION}}
